CATEGORY_MAP = {
    "OPEN": [
        "GOPENH",
        "GOPENO",
        "GOPENS",
        "LOPENH",
        "LOPENO",
        "LOPENS",
    ],
    "OBC": [
        "GOBCH",
        "GOBCO",
        "GOBCS",
        "LOBCH",
        "LOBCO",
        "LOBCS",
    ],
    "SC": [
        "GSCH",
        "GSCO",
        "GSCS",
        "LSCH",
        "LSCO",
        "LSCS",
    ],
    "ST": [
        "GSTH",
        "GSTO",
        "GSTS",
        "LSTH",
        "LSTO",
        "LSTS",
    ],
    "VJ": [
        "GVJH",
        "GVJO",
        "GVJS",
        "LVJH",
        "LVJS",
    ],
    "NT1": [
        "GNT1H",
        "GNT1O",
        "GNT1S",
        "LNT1H",
        "LNT1S",
    ],
    "NT2": [
        "GNT2H",
        "GNT2O",
        "GNT2S",
        "LNT2H",
        "LNT2S",
    ],
    "NT3": [
        "GNT3H",
        "GNT3O",
        "GNT3S",
        "LNT3H",
        "LNT3S",
    ],
    "SEBC": [
        "GSEBCH",
        "GSEBCO",
        "GSEBCS",
        "LSEBCH",
        "LSEBCO",
        "LSEBCS",
    ],
    "EWS": [
        "EWS",
    ],
    "TFWS": [
        "TFWS",
    ],
    "MI": [
        "MI",
    ],
    "ORPHAN": [
        "ORPHAN",
    ],
    "PWD": [
        "PWD",
        "PWDOBCH",
        "PWDOBCS",
        "PWDOPENH",
        "PWDOPENS",
        "PWDRNT1H",
        "PWDRNT1S",
        "PWDRNT2H",
        "PWDRNT2S",
        "PWDRNT3S",
        "PWDROBC",
        "PWDRSCH",
        "PWDRSCS",
        "PWDRSEBC",
        "PWDRSTH",
        "PWDRSTS",
        "PWDRVJS",
        "PWDSCH",
        "PWDSCS",
        "PWDSEBCS",
        "PWDSTS",
    ],
    "DEFENSE": [
        "DEFOBCS",
        "DEFOPENS",
        "DEFRNT1S",
        "DEFRNT2S",
        "DEFRNT3S",
        "DEFROBCS",
        "DEFRSCS",
        "DEFRSEBC",
        "DEFRSTS",
        "DEFRVJS",
        "DEFSCS",
        "DEFSEBCS",
        "DEFSTS",
    ],
}


DISPLAY_CATEGORIES = sorted(CATEGORY_MAP.keys())
